import { Inter, Maitree } from "next/font/google";
import "./globals.css";
import Footer from "./Footer";
import MainBody from "./MainBody";

const inter = Inter({ subsets: ["latin"] });
const balthazar = Maitree({
  subsets: ["latin"],
  weight:['500'],
  style: ['normal'],
})
function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${balthazar.className} max-w-screen-maxW m-auto box-border bg-[#F7F7F7]`}>
        <MainBody children={children}/>
        {/* <Footer/> */}
        </body>
    </html>
  );
}
